### ISSUE TITLE
As a user, I want to be able to move my character so that I can position myself to defend the village.

### ISSUE THREAD

**Issue by RealSnowKid** [Luanrstorm-Entertainment/UntitledVideoGame#7]
- [x] Learn how Unity's new input systems work.
- [x] Test/use Unity's Third Person Controller Asset.
- [x] Find a free Wizard Asset so that we can use it for our Sprint 1 presentation.
- [x] Replace the Wizard Asset with Unity's standard character.
- [x] Learn how animations work in Unity. (Animation Controller)
- [x] Replace the animations with Wizard animations.
- [x] Add an aim or attack input system to use for basic attacking.

**Comment by oererenn** [comment]
- [ ] Learn how Unity's new input systems work.
- [ ] Test/use Unity's Third Person Controller Asset.
- [ ] Find a free Wizard Asset so that we can use it for our Sprint 1 presentation.
- [ ] Replace the Wizard Asset with Unity's standard character.
- [ ] Learn how animations work in Unity. (Animation Controller)
- [ ] Replace the animations with Wizard animations.
- [ ] Add an aim or attack input system to use for basic attacking.

**Comment by RealSnowKid** [comment]
Closed by #26
